Repository RedHatQE/python-utility-scripts, pull requests merged in 2024-04, with the labels that each got.

#6 Add polarion test requirement verification script
  .gitignore
  README.md
  apps/polarion/README.md
  apps/polarion/__init__.py
  apps/polarion/polarion_utils.py
  apps/polarion/polarion_verify_tc_requirements.py
  apps/unused_code/README.md
  apps/unused_code/unused_code.py
  apps/utils.py
  config.example.yaml
  poetry.lock
  pyproject.toml
  pytest.ini
  tests/polarion/__init__.py
  tests/unused_code/test_unused_code.py
  tests/utils.py
  tox.ini
Labels: size/XL, branch-main

#27 Polarion script: add tests
  apps/polarion/polarion_utils.py
  apps/polarion/polarion_verify_tc_requirements.py
  poetry.lock
  pyproject.toml
  tests/polarion/test_verify_polarion_requirements.py
Labels: verified, size/M, can-be-merged, branch-main, approved-dbasunag

#30 base PR for set polarion as automated
  apps/polarion/polarion_set_automated.py
  apps/polarion/polarion_utils.py
  apps/polarion/polarion_verify_tc_requirements.py
  config.example.yaml
  poetry.lock
  pyproject.toml
  tests/polarion/test_polarion_automated.py
Labels: verified, size/L, branch-main

#34 Revert "base PR for set polarion as automated"
  apps/polarion/polarion_set_automated.py
  apps/polarion/polarion_utils.py
  apps/polarion/polarion_verify_tc_requirements.py
  config.example.yaml
  poetry.lock
  pyproject.toml
  tests/polarion/test_polarion_automated.py
Labels: size/L, branch-main

#38 add mypy and update files
  .pre-commit-config.yaml
  apps/polarion/polarion_utils.py
  apps/polarion/polarion_verify_tc_requirements.py
  apps/unused_code/unused_code.py
  apps/utils.py
  poetry.lock
  pyproject.toml
Labels: size/M, branch-main, changes-requested-rnetser

#40 Do python typing right
  apps/polarion/polarion_utils.py
  apps/polarion/polarion_verify_tc_requirements.py
  apps/unused_code/unused_code.py
  apps/utils.py
  poetry.lock
  pyproject.toml
  pytest.ini
  tox.ini
Labels: verified, size/M, can-be-merged, branch-main, approved-dbasunag, approved-rnetser
