Repository RedHatQE/python-utility-scripts, pull requests merged in 2024-03, with the labels that each got.

#20 Fix when in some cases func do not have attr
  apps/unused_code/unused_code.py
Labels: verified, size/XS, can-be-merged, branch-main, approved-dbasunag

#22 remove unnecessary package requirements
  poetry.lock
  pyproject.toml
Labels: verified, size/XXL, can-be-merged, branch-main, approved-myakove

#24 add pyyaml
  poetry.lock
  pyproject.toml
Labels: verified, size/M, can-be-merged, branch-main, approved-myakove
