Repository RedHatQE/python-utility-scripts, pull requests merged in 2025-03, with the labels that each got.

#153 polarion_approve_automate() should compare commit hashes to get the git diff.
  apps/polarion/polarion_set_automated.py
  apps/polarion/polarion_utils.py
  tests/polarion/test_polarion_automated.py
Labels: verified, size/M, can-be-merged, branch-main, approved-myakove

#162 Move to `uv` for manage the project
  .release-it.json
  README.md
  poetry.lock
  pyproject.toml
  tox.ini
  uv.lock
Labels: verified, size/XXL, can-be-merged, branch-main, approved-rnetser, commented-coderabbitai[bot]

#164 Skip unused code for functions
  apps/unused_code/README.md
  apps/unused_code/unused_code.py
  pyproject.toml
  tests/unused_code/test_unused_code.py
  tests/unused_code/unused_code_file_for_test.py
  uv.lock
Labels: verified, size/M, can-be-merged, branch-main, approved-dbasunag, approved-rnetser, commented-myakove
